# -*- coding: utf-8 -*-
"""Assignment-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a-UxcI1EUZJKbaxRbdffdnKFZidRnyed
"""

#Assignment -4  => If-else-elif
for i in range(3):
  currentAltitude = int(input(" Enter Current altitude : "))
  if currentAltitude <= 1000:
    print(' Safe to land ')
  elif currentAltitude >1000 and currentAltitude <=5000:
    print(' Come down to 1000ft ')
  else:
    print(" Go around and try later ")

