# -*- coding: utf-8 -*-
"""Assignment-5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XeffrhmT-8NX-D5Nh1sHATTg7hMIZqfE
"""



#find prime number
getNumber=int(input('Enter Number : '))
checkCount = 0
loopCount = 2;
while (loopCount <=  getNumber/2 ):
  if(getNumber%loopCount == 0):    
    checkCount = checkCount+1
    break
  loopCount = loopCount+1

if(checkCount == 0 ):
  print('It is a Prime Number')
else:
  print('It is Not a Prime Number')

! pip install pytube

from pytube import YouTube
YouTube('https://youtu.be/Ma1AaMRNgrQ').streams.first().download('d://')

