# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_4AJ4R-Csm5-p6NdG3KWjtxn1WK8y7I
"""

#------------------List Methods-----------------------
firstList = []
secondList = []

for i in range(5):
  getValue= input("Enter First list element : ")
  firstList.append(getValue)

print("First List : ",firstList)

for i in range(3):
  getValue= input("Enter second list element : ")
  secondList.append(getValue)

print("second List : ",secondList)

copyList=firstList.copy()
print("Copy First List : ",copyList)

countList = firstList.count('pp')
print("count First List : ",countList)

extendList = firstList.extend(secondList)
print("Extend List : ",firstList)

indexOfList = firstList.index("pp")
print("index Of List : ",indexOfList)

insertInList = secondList.insert(1, "s-4")
print("Insert List : ",secondList)

reverseList = firstList.reverse()
print("Reverse List : ",firstList)

sortList = firstList.sort()
print("Sort List : ",firstList)

popListelement = firstList.pop(2)
print("Pop List : ",firstList)

removeListelement = firstList.remove('pp')
print("Remove List : ",firstList)

 clearList=copyList.clear()
 print("clear Copy List : ",copyList)


#-------------------Dict Method----------------
firstDict = {"name":"komal","education":"BE","city":"Mumbai"}
secondDict = {"name":"namrata","education":"BE","city":"Thane"}
print("First List : ",firstDict)
print("second List : ",secondDict)

copyDist=firstDict.copy()
print("Copy First Dict : ",copyDist)

fromkeysDict = firstDict.fromkeys(firstDict,1)
print("fromkeys Dict : ",fromkeysDict)

getdict = firstDict.get("city")
print("get Dict : ",getdict)

popdict = firstDict.pop("city")
print("Pop Dict : ",popdict)

valuesDist = firstDict.values()
print("values First Dict : ",valuesDist)

