# -*- coding: utf-8 -*-
"""firstcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eG3P4sTkj3_5HNob64LEm6aik1c4b-p2
"""

#Substarction 
sub_num1 = int(input("Enter first Number : "))
sub_num2 = int(input("Enter Second Number : "))
sub_res = sub_num1 - sub_num2
result = print('substraction result is : ' ,sub_res)

#Multiplication
mul_num1 = int(input("Enter first Number : "))
mul_num2 = int(input("Enter Second Number : "))
mul_res = mul_num1 * mul_num2
result = print('multiplication result is : ' ,mul_res)

#division
divi_num1 = int(input("Enter first Number : "))
divi_num2 = int(input("Enter Second Number : "))
divi_res = divi_num1 / divi_num2
result = print('division result is : ' ,divi_res)

