# -*- coding: utf-8 -*-
"""lotteryProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TCnj0t7teQ66TB0SWevh7FLKVMQh5095
"""

totalLotteryTickets = 15
allUsers = ["komal","vijay","harshada","gaurav","yogesh","namarta","rahul","neha","nisha","vihan","khushi","harsh","vedika","tina","shital"]
import random
print('List of Two Lottery Winners')
for i in range (2):
 
  lotteryWinnner = random.randint(0,totalLotteryTickets-1)
  displayWinnerName = allUsers[lotteryWinnner]
  j=i+1
  print('Lottery Winner', j ,' : ',displayWinnerName)

